### ISSUE TITLE
example 1 exception

### ISSUE THREAD

**Issue by marcinic** [jimlindstrom/FinModeling#3]
I'm having trouble running the examples out of the box. I installed with 'gem install finmodeling'. 

$ ruby show_reports.rb --num-forecasts 2 --do-valuation orcl 2012-02-01
Forecasting 2 periods
Doing valuation
company name: ORACLE CORP
show_reports.rb:133:in `rescue in block in <main>': uninitialized constant FinModeling::InvalidFilingError (NameError)
    from show_reports.rb:129:in`block in <main>'
    from show_reports.rb:128:in `each'
    from show_reports.rb:128:in`<main>'

**Comment by jimlindstrom** [comment]
Hey Marcinic - thanks for reporting this issue. Happy to look at it with you.

I have a suspicion that maybe I haven't been disciplined about two important things: (1) Bumping up the gem's version as I make changes, and (2) republishing to rubygems. RubyGems (https://rubygems.org/gems/finmodeling) shows a last push on March 31, 2012, which sounds _really_ old.

This weekend, I can make sure that I've got the latest versions of all the relevant gems pushed to rubygems. In the meantime, could you try building the gem from this repo and seeing if that solves your problem? If not, this might be a legitimate bug.

jbl

**Comment by jimlindstrom** [comment]
Actually, I just went ahead and pushed the latest versions now. There are new versions of xbrlware-extras (1.1.2.19.3) and finmodeling (0.2) out there now. 

Try those and let me know if you still have this issue.

**Comment by marcinic** [comment]
Hi Jim,

Thanks for your response and for making this really cool library. In your
update, nasdaq_query appears not to be on the rubygems site and is causing
a dependency error. I'm still familiarizing myself with the code base but I
would like to help out with this project any way I can.

-Chris

On Fri, Aug 23, 2013 at 7:05 PM, Jim Lindstrom notifications@github.comwrote:

> Hey Marcinic - thanks for reporting this issue. Happy to look at it with
> you.
> 
> I have a suspicion that maybe I haven't been disciplined about two
> important things: (1) Bumping up the gem's version as I make changes, and
> (2) republishing to rubygems. RubyGems (
> https://rubygems.org/gems/finmodeling) shows a last push on March 31,
> 2012, which sounds _really_ old.
> 
> This weekend, I can make sure that I've got the latest versions of all the
> relevant gems pushed to rubygems. In the meantime, could you try building
> the gem from this repo and seeing if that solves your problem? If not, this
> might be a legitimate bug.
> 
> jbl
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jimlindstrom/FinModeling/issues/3#issuecomment-23196685
> .

## 

Chris Marciniak
202-365-0502
http://marcisuntimes.com

**Comment by jimlindstrom** [comment]
Yikes. I obviously haven't done enough testing of this outside my development environment. I just pushed nasdaq_query as a new gem. I also verified that I am now able--from an clean, empty gemset--to "gem install finmodeling" and run then run one of the example scripts. Hopefully it'll work for you now, too.

Any help you're interested in contributing would be much appreciated! Can I ask what you're thinking of using the gem for, or how you could imagine improving/extending the gem?

**Comment by marcinic** [comment]
The gem install worked after installing gsl-1.14.  It might be worth
putting that in the readme since its the only non-ruby dependency.

I'm looking to do ratio analysis and possibly serve it up on the web.
 Other than that I think the SEC's XBRL collection is a really important
data-set and one that I want to have a programmatic handle on. I'm happy to
test things, do quality assurance type stuff, maybe practice some TDD.

On Sat, Aug 24, 2013 at 2:56 PM, Jim Lindstrom notifications@github.comwrote:

> Yikes. I obviously haven't done enough testing of this outside my
> development environment. I just pushed nasdaq_query as a new gem. I also
> verified that I am now able--from an clean, empty gemset--to "gem install
> finmodeling" and run then run one of the example scripts. Hopefully it'll
> work for you now, too.
> 
> Any help you're interested in contributing would be much appreciated! Can
> I ask what you're thinking of using the gem for, or how you could imagine
> improving/extending the gem?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jimlindstrom/FinModeling/issues/3#issuecomment-23214339
> .

## 

Chris Marciniak
202-365-0502
http://marcisuntimes.com

**Comment by jimlindstrom** [comment]
Glad you're up and running now. I updated README.md -- good suggestion.

Cool, if you do end up making some contributions, I'd be happy to review and accept them. My own to do list (which I haven't touched in months) is in TODO.txt. Some of them are quite difficult, if you don't know the codebase well; but some are quite easy.
